// Single source of truth for client reviews shown on /reviews/ and for the
// AggregateRating reviewCount used in JSON-LD across the site.
// Add new reviews to the top of the relevant section array; the count derives itself.

export interface Review {
  author: string
  rating: number
  source: string
  note?: string
  text: string
}

export const section1Reviews: Review[] = [
  { author: 'Elizabeth W.', rating: 5, source: 'Google', text: 'Marie is an expert portrait photographer! I had a great time at the shoot, and I came away with some gorgeous photos.' },
  { author: 'Jackie R.', rating: 5, source: 'Google', text: 'Marie was amazing to work with. The environment was so relaxed. Marie didn\'t rush anything yet at the same time she was so efficient. You can tell she has so much experience doing this as she is easy breazy, professional, talented and fun.' },
  { author: 'Heidi L.', rating: 5, source: 'Google', text: 'Hands down, best head shots EVER!! And… Marie is absolutely wonderfully lovely to work with. Kindness, excellence and joy all at the same time. 🙏🏻♥️😘' },
  { author: 'Edna S.', rating: 5, source: 'Google', text: 'I had a glorious time having my headshots by Marie. The results say it all. I would recommend her hand over fist. :) wink' },
  { author: 'Chad W.', rating: 5, source: 'Google', text: 'Thank you for the experience, Marie! You cultivated a very comfortable atmosphere in your studio. I appreciated the amount of time you dedicated to our session, as it never felt rushed.' },
  { author: 'Jennifer E.', rating: 5, source: 'Google', text: 'Marie is a miracle worker! She turned a headshot photoshoot-- something I was truly dreading-- into a fantastic experience. Her work is absolutely stunning; I\'m struggling to choose my favorite shot because there are so many great ones. Thank you, Marie, for making me look and feel my best!!' },
  { author: 'Guacy B.', rating: 5, source: 'Google', text: 'Working with Marie for my branding and headshot session was an absolute dream. From start to finish, she showcased incredible professionalism, patience, and attention to detail. This wasn\'t just a photoshoot, it was an experience that exceeded all my expectations. Marie\'s expertise in lighting, positioning, and creating the perfect atmosphere was evident throughout the entire session. Despite multiple outfit changes and adjustments, she remained patient, focused, and full of creative energy and joy. She made sure every detail was just right, offering valuable guidance while allowing me to express my personality and brand vision. I had a hiccup before one of my outfits, and Marie came to the rescue! She was not only prepared but also genuinely helpful in finding solutions on the spot. Her preparedness, attentiveness to honoring my vision, resourcefulness, and calm demeanor turned what could have been a stressful situation into a seamless experience. What also stood out was her warm and welcoming personality. She made me feel comfortable and confident in front of the camera, and even treated me to a delicious coffee that fueled our creative energy for the day. Nice music and comfortable atmosphere. The final photos were nothing short of breathtaking. Marie captured my essence and brand perfectly, and I couldn\'t be happier with the results. She truly has a gift for bringing out the best in her clients and creating images that tell a story. If you\'re looking for a photographer who is not only talented but also a joy to work with, I can\'t recommend Marie highly enough. Whether for headshots, branding, or any other photography needs, she is the ultimate professional who will go above and beyond to deliver outstanding results and that is very difficult to find nowadays. Thank you, Marie, for your incredible work and for making this such an unforgettable experience!' },
  { author: 'Michael G.', rating: 5, source: 'Google', text: 'Marie gets an AAA+++ from me and I HIGHLY recommend her. She is a true professional. I have had headshots taken many times before, but her process is truly unique! She encourages you to bring multiple outfits, makes you feel comfortable, gets to know you and your objective first and you never feel rushed. The photos she took of me EXCEEDED my expectations!! Bravo Marie!!!' },
  { author: 'Derrick J.', rating: 5, source: 'Google', text: 'I couldn\'t have asked for a more inviting, professional, and memorable experience! The extensive knowledge and attention to every detail showed up in my amazing final photos. From ensuring I was comfortable with positioning or the well-timed and thoughtful instruction that was provided. Every moment was well-executed, and most importantly, based on my preferences and desired outcomes. Highly recommended...always!' },
  { author: 'Andy H.', rating: 5, source: 'Google', text: 'Marie was wonderful to work with for my residency headshots and I would definitely recommend her to anyone considering hiring a professional. She helped me feel comfortable in front of the camera and gave lots of tips on how to pose so my facial expressions photographed well. She was friendly and funny which helped evoke a genuine smile. Marie took a ton of photos and as we were shooting she was picking out the best ones to come back to later. I changed my shirt and tie a few times while she changed the backgrounds so we had several different looks to choose from. After a while, we reviewed the highlights reel and discussed our favorites. We shot a couple more photos with those features in mind and then went back to narrow it down to my favorite 2 shots. I was very happy with the end results even before she touched them up. Within a few days of the shoot she sent me the final edited headshots in both high and low resolution.' },
  { author: 'Tommy L.', rating: 5, source: 'Google', text: 'Marie did a fantastic Job! I came into the experience with the goal of just updating my LinkedIn photos for work, but I left with a new appreciation for photography, lighting, directing and posing as Marie seamlessly explained and taught me these arts/sciences throughout the session. I thought that the process might be boring, but I could not have been more wrong. I had a fantastic time. If you\'re looking to get professional photos done or just want a fantastic gift for a loved one don\'t look any further than Headshots by Marie.' },
  { author: 'Natalie', rating: 5, source: 'Google', text: 'I recently had a headshot session with Marie who exceeded all expectations. She was consultative, capturing the exact brand image I wanted, and her communication was excellent throughout. The experience was smooth and comfortable, and the final photos perfectly reflect my professional image. Highly recommended!' },
  { author: 'Forrest G.', rating: 5, source: 'Google', text: 'I recently had the pleasure of working with Marie for a headshot photo shoot, and I couldn\'t be more thrilled with the entire experience. Right from the start, her professional approach, paired with a genuinely warm personality, made me feel comfortable and confident. One of the key aspects that set Marie apart is their remarkable attention to detail. She has a keen eye for light, angles, and composition, which was evident in how meticulously she set up each shot. Her thoughtful adjustments to my posture, positioning, and even the slight changes in facial expressions were impressive. It\'s clear she understands how the smallest details can make a significant difference in the final result.' },
  { author: 'Cynthia T.', rating: 5, source: 'Google', text: '5 stars just doesn\'t do Marie justice. She is both approachable and professional. I was able to have an extremely efficient photo shoot as she shared her expert knowledge of how to make people look their best in a headshot photo for any profession. She provided an insanely fast turnaround time for my photos, and I\'m more than happy with them. Thank you, Marie!' },
  { author: 'Rob H.', rating: 5, source: 'Google', text: 'I was new to headshots and knew I wanted personal branding. Marie used her expertise to coach me, putting me at ease and truly achieving a look that I love. I cannot wait to go back to her for another session. She is both world-class in technique and down to earth in personality so you will love working with her. Marie not only achieved the look I was going for, but introduced me to the styles and photographers she loves too. She guided me to select photographs that would serve me with her excellent sense of style. Thank you Headshots by Marie, until next time.' },
  { author: 'Anne M.', rating: 5, source: 'Google', text: 'I contacted Marie because I needed photos for a press release and new website. She was responsive and professional, answering my questions and providing rates for her services. Working with her in her studio was FUN! I brought several clothing options and we played. I LOVE the photos as they reflect my personal brand in a fun and professional way. I highly recommend Marie.' },
  { author: 'Anne M.', rating: 5, source: 'Google', text: 'Marie is amazingly talented. She takes time to get to know her clients so she can deliver the portraits they desire.' },
  { author: 'Anthony D.', rating: 5, source: 'Google', text: 'Marie was a joy to work with and the headshots came out fantastic. I wanted a specific theme/feel for my photos and she went out of her way to make that happen. I will definitely be using her again for my next project.' },
  { author: 'Eric S.', rating: 5, source: 'Google', text: 'Marie is a master of her craft. She loves photography and it shows. She did a great job with my photos. I couldn\'t be happier.' },
  { author: 'Harvey S.', rating: 5, source: 'Google', text: 'Great experience working with Marie. She made the session fun, worked with my ideas as well as giving plenty of her own input, with the result of plenty of excellent images to choose from. Recommended!' },
  { author: 'Emeline A.', rating: 5, source: 'Google', text: 'Marie was wonderful to work with. She brings your vision to life with ease, making the entire process feel natural and enjoyable. Her calm professionalism made the shoot an excellent experience, and I\'m very pleased with how the photos turned out. I highly recommend her!' },
  { author: 'Aaron C.', rating: 5, source: 'Google', text: 'Marie was so good to work with. She thought through every detail and worked to bring out the best shots possible. I would very much work with her again!' },
  { author: 'Brenda C.', rating: 5, source: 'Google', text: 'I recently visited Marie for a headshot and I truly enjoyed the experience. Marie took the time to understand what I was looking for and made sure it was perfect. I really appreciate the time she took to make me feel comfortable and ensuring the final product would be exactly what I wanted. Thank you Marie!' },
  { author: 'Alex S.', rating: 5, source: 'Google', text: 'Marie was amazing, very welcoming and expert level knowledge on how to get the right picture captured for the style and look I was looking for. Will use again in the future!' },
  { author: 'Erich S.', rating: 5, source: 'Google', text: 'Marie is nothing short of outstanding! She took amazing photos of my fiance and myself that would be the envy of anyone. If you want to look professional and polished, hire Marie!' },
  { author: 'Chris C.', rating: 5, source: 'Google', text: 'Marie was very professional. She did a great job showing my personality in the photos. It was a pleasure having her take my pictures. I highly recommend her.' },
  { author: 'Shawn D.', rating: 5, source: 'Google', text: 'Great experience. Very knowledgeable and professional!' },
  { author: 'Larry S.', rating: 5, source: 'Google', text: 'Marie is great to work with and always does a fantastic job!' },
  { author: 'Brenda D.', rating: 5, source: 'Google', text: 'Marie is amazing! She was quick and professional. I cannot wait to see the final result.' },
  { author: 'Samuel Q.', rating: 5, source: 'LinkedIn', text: 'I have known Marie for almost eight years. The two of us were in the same business group. She has always been a first class person and it truly shows in her work. The passion she has for making people look their best is unmatched. What is also great is she has grown into a leader and she is able to hold one of the top positions in the business group in addition to building her growing photography studio.' },
  { author: 'Angie K.', rating: 5, source: 'LinkedIn', text: 'No ordinary but EXTRAORDINARY is the photography by Marie. She is able to see what others cannot and she captures that in each headshot she does. She spends time getting to know each client. You will not find anyone superior to her passion and dedication to creating the headshot that will perfectly capture you!' },
]

export const section2Reviews: Review[] = [
  { author: 'Margot W.', rating: 5, source: 'Google', text: 'I highly recommend Marie as your professional photographer, I am beyond thrilled with my results!!! I have never felt so good about seeing myself in a picture and I have had several studio sessions over the course of many years. Marie is warm, friendly, patient, she gives you her full attention and makes you feel at ease and at home. Her work is thoughtful, creative, insightful, decisive, professional and I left with incredible results in a timely manner. Thank you Marie from the bottom of my heart, I really enjoyed my session. You have given me a new spark and I cannot thank you enough!!!' },
  { author: 'Russell T.', rating: 5, source: 'Google', text: 'Upon arrival, I was an hour early at my own fault. Marie, however adjusted very quickly and received me with a warm and smiling greeting and ensured it was no difficulty to begin an hour early. This is my first time having headshots done and an extreme critic of my own self in photos, Marie took charge and began directing me in a manner in which I felt very comfortable and relaxed. She was very meticulous about the set up and preparation prior to our session beginning. This too confirmed that I had selected the right photographer for my photographs. Very comfortable setting with an area to change into secondary attire. We reviewed all pics taken and retook a few in different poses to ensure we got the best images possible. Again, I am a HUGE critic of myself and run from cameras, but Marie had taken a couple that even I was proud of. We finalized on four the she and I both agreed were the best. The prices based on my search prior to selecting her were more than fair and the final product was worth it!!!!!' },
  { author: 'Ali H.', rating: 5, source: 'Google', text: 'Marie is magical! She\'s calm and confident which instills calmness and confidence in her subjects. I entered the session ready to list off my insecurities. She assessed my outfits, recommended the top two and off we went! A quick test shot under her professional lighting and lens whisked away any concerns I came in with. Start to finish, the session was joyful and efficient. She guides you on how to pose and captures different angles so you can choose your best side. It was a comprehensive session and worth every cent of the investment. Show the world your best side! You deserve it.' },
  { author: 'Jesslyn W.', rating: 5, source: 'Google', text: 'Fantastic experience and photos! I have never liked myself in photographs. I simply do not resolve well on film but Marie was able to capture all the best of me. From the perfect preparation reminders to the personalized board greeting me at the entry, the whole experience was delightful. She is professional and puts you at ease. I never felt rushed, changed outfits several times, and her prompts were perfect for getting the right kinds of headshots I needed. And her pricing is wonderful! Will be coming back for anniversary photos with my husband soon.' },
  { author: 'Gladys G.', rating: 5, source: 'Google', text: 'This was my 1st professional photo shoot and I couldn\'t have asked for a better photographer than Marie. She made me feel comfortable since the moment I walked in. She greeted me with a sign outside which made me feel special. Once we started the shoot, I could tell she knew what she was doing when I saw her working with all the lights and backgrounds. She did practice pictures to make sure the lighting was perfect which I appreciated it. She didn\'t make me feel rushed, she took her time to make sure the pictures came out just right. She made the shoot fun, making me laugh. It took a few days to get my pictures back and let me say I was stunned by her work. They were perfection. If you are going to trust someone with your pictures, Marie is the one to call.' },
  { author: 'Dave Z.', rating: 5, source: 'Google', text: 'Marie was so wonderful to work with. Being in front of the camera can be intimidating but she made it a very fun and relaxing experience! The quality of her work is incredible and I am so happy with my headshots and portraits. She took so many fantastic photos it was hard to narrow it down to a few. I HIGHLY recommend Marie if you need headshots or portraits. Best photographer I have ever worked with!' },
  { author: 'Scott G.', rating: 5, source: 'Google', text: 'I did a shoot with Marie and the photos turned out amazing! But what really stood out was how comfortable she made me feel throughout the session \u2014 something I\'ve rarely experienced with other photographers. She has a way of making the whole process fun and relaxed, which brought out my best side in the pictures. Couldn\'t recommend her more!' },
  { author: 'Martha D.', rating: 5, source: 'Google', text: 'AMAZING! I was so nervous to get head shots done for the first time. I don\'t like pictures of myself to begin with but needed them for professional reasons. But the entire experience was amazing! I left excited to do it again! Best part is I love the pictures and look forward to using them and telling everyone how incredible my experience was at Headshots by Marie!!' },
  { author: 'Carissa C.', rating: 5, source: 'Google', text: 'Just got my headshots completed by Marie and the experience was an absolute fairytale. I never had professional photos before so as you can imagine, I was nervous. The entire shoot was just incredible and the talent that she has shows as soon as the camera turned on. It was awesome to see her impeccable work and also to be the one in front the camera. Never felt more gorgeous in my entire life. Thank you Marie!' },
  { author: 'Alex V.', rating: 5, source: 'Google', text: 'Marie is amazing! I was nervous because I always shy away from the camera, but Marie made it easy. She knows exactly how to direct you, and make it a great experience. I\'m so lucky I found her. Thank you for everything!' },
  { author: 'Mike S.', rating: 5, source: 'Google', text: 'Such a great experience and Marie is such a professional! I was not excited about doing my head shots and Marie made it a lot of fun. Professional and very reasonable. Thank you Marie!' },
  { author: 'Lydia V.', rating: 5, source: 'Google', text: 'Marie is exceptional about making the process very easy. I am definitely camera shy, and the session was simple, conversational and the photos are quite possibly the best that have ever been captured of me. 10/10 would recommend.' },
  { author: 'Matt M.', rating: 5, source: 'Google', text: 'Marie did an incredible job with my photos. She has a way of making you feel comfortable and getting the best poses. Highly recommend!!' },
  { author: 'Julie B.', rating: 5, source: 'Google', text: 'Marie was wonderful to work with. She made me comfortable from the start, helped me know how to pose to create the best looking photos, and the results were incredible. I would definitely recommend her for your next headshots.' },
  { author: 'Jan W.', rating: 5, source: 'Google', text: 'Marie provided an enjoyable and professional experience from beginning to end. The resulting headshots were exactly what I was looking for. Marie exceeded my expectations, making the process welcoming, easy, fun, and collaborative. Highly recommended!' },
  { author: 'Patrick P.', rating: 5, source: 'Google', text: 'Marie was wonderful to work with. It seems to always be awkward when you have to pose for photos but she put me and my team at ease and made it an enjoyable process. I recommend her highly.' },
  { author: 'Adam D.', rating: 5, source: 'Google', text: 'Wow, not only am I impressed with the quality of the photography, I am genuinely pleased with the service. Marie was fun, helpful and reassuring to ensure the best quality photos would be produced. I will certainly recommend her to my colleagues and 100% happy with the experience.' },
  { author: 'Maryam B.', rating: 5, source: 'Google', text: 'Marie is wonderful! First thing you\'ll notice is her personality and hospitality. She makes you feel comfortable and she takes her time. She really loves what she does and I am really glad that I found her. I highly recommend her!' },
  { author: 'Andrea M.', rating: 5, source: 'Google', text: 'Very pleased with my photos from Headshots by Marie. Marie made me feel so comfortable! Highly recommend!!! Thank you, Marie!!' },
  { author: 'Melanie B.', rating: 5, source: 'LinkedIn', text: 'I never take a good photo. Marie is a magician with lighting. If you need a professional headshot, I encourage you to seek her out!' },
]

export const section3Reviews: Review[] = [
  { author: 'Keith S.', rating: 5, source: 'Google', note: 'actor', text: 'Love working with a professional like Marie taking pictures of my headshotS She was very well organized and knew exactly what agencies look at for actors and made me feel very comfortable' },
  { author: 'John B.', rating: 5, source: 'Google', note: 'SAG actor', text: 'After 25 years of getting acting headshots in Chicago and Los Angeles I was nervous about getting headshots in Phoenix. BUT Marie was so professional and so keyed in to what I wanted. She understood the difference between my old shots and what I wanted from these new ones. I think they are wonderful and will open new doors and MORE doors for me in my acting. I will use her again and tell everyone to give her a chance. You won\'t be disappointed! She is awesome!!!' },
  { author: 'Kayli B.', rating: 5, source: 'Google', text: 'Marie is the best! I knew her photos had an art that the others didn\'t. But I didn\'t know Marie would be so kind. She gave me a military Black Friday deal. I had to reschedule twice which she let me do without charge. She shot my headshots with only two hours notice and made herself available when my schedule permitted, which was hard for me because I\'m leaving the military so everything has been crazy and Marie came through for me. She offers unlimited time. So it\'s not like other photographers where you have to feel rushed, it was relaxing and she worked with lighting until she got the style I was going for in my inspo pictures, and she said it was a fun challenge. We had a great time, it was lovely to see her work she is a true pro with lighting and cameras. She is constantly developing her skill and art and I highly recommend her. She was wonderful.' },
  { author: 'Rachel S.', rating: 5, source: 'Google', text: 'This is my second time using Marie and as expected she is a delight to work with and I\'m so happy with my headshot!!' },
  { author: 'Candice W.', rating: 5, source: 'Google', text: 'I would recommend Marie to anyone. She was fantastic! She made the whole process very easy. The results were amazing! She was very informative and professional. Easy location to find. All around perfect experience! Exceeded my expectations by far!' },
  { author: 'Mary E.', rating: 5, source: 'Google', text: 'We loved working with Marie in getting our individual and team professional headshots! Her expertise in portrait photography is exceptional! We highly recommend Headshots by Marie!' },
  { author: 'Ron M.', rating: 5, source: 'Google', text: 'First time session with Marie. I had pictures taken for new, updated headshots and they turned out AMAZING! I\'m very happy with editing and outcomes of my pictures. She made the session very fun and I was open to her directions. I will definitely be recommending to my network. Her prices were fair and comparable to other photographers I researched. Thank you again, Marie!' },
  { author: 'Serban', rating: 5, source: 'Google', text: 'Fantastic picture, but even more, fantastic experience. Marie\'s work is incredible, but I also felt understood and welcomed through the whole process. So much professionalism. Merci, Marie!!' },
  { author: 'Crystal L.', rating: 5, source: 'Google', text: 'Marie was great! She made me feel at ease and helped me look my best in the headshot photos. Thank you, Marie!' },
  { author: 'Jennifer G.', rating: 5, source: 'Google', text: 'Marie was amazing! She helped me feel comfortable and got to know ME so that my personality translated in the photos. Thank you again, Marie!' },
  { author: 'DeShawn A.', rating: 5, source: 'Google', text: 'Fantastic job working with Ms. Marie, I loved my head shots and time flew by capturing them. Would recommend 10/10.' },
  { author: 'Thomasina C.', rating: 5, source: 'Google', text: 'I had such a great experience getting my photo taken by Marie. The results were amazing, but what really stood out was her ability to make me feel comfortable while getting my photo taken. She went above and beyond to ensure I was completely happy with my photo. Her attention to detail and responsiveness to my additional request continued to display her care for her customers. Thanks Marie!' },
  { author: 'Kesha B.', rating: 5, source: 'Google', text: 'My experience was absolutely wonderful! Marie made me feel very comfortable and welcome. My pictures came out great! I would definitely recommend her.' },
  { author: 'McCall B.', rating: 5, source: 'Google', text: 'Great overall experience and the photos were delivered very quickly!' },
  { author: 'Gina M.', rating: 5, source: 'Google', text: 'Marie is wonderful! I have been going to Headshots by Marie for the past two years for all my employee headshots. She makes everyone feel very welcome and comfortable. Not only that, our photos turn out beautiful! She is an incredibly gifted photographer.' },
  { author: 'Kelsey P.', rating: 5, source: 'Google', text: 'Marie was absolutely amazing! She created a relaxing and fun environment, which helped me feel at ease. Marie\'s energy was contagious and resulted in the perfect experience.' },
  { author: 'Renee O.', rating: 5, source: 'Google', text: 'Marie was very professional and a joy to work with!! I love my photos and would highly recommend her to anyone looking for professional shots!' },
  { author: 'Joy O.', rating: 5, source: 'Google', text: 'Marie was truly a pleasure to work with! My family of 4 arrived a bit out of sorts and she quickly helped to turn the mood around and helped the whole family to have fun with the shoot! The fact we had fun also showed in the pictures. We got great family shots and individual shots. It was nice to have many different backgrounds and poses to choose from. Thank you Marie! We will definitely call again for future photography needs.' },
  { author: 'Janelle S.', rating: 5, source: 'Google', text: 'Marie is an amazing photographer. I had such a wonderful time taking my portraits with her. She is very kind, helps you become comfortable in front of the camera, and the portraits came out amazing. I loved working with Marie and her team!' },
  { author: 'Kat K.', rating: 5, source: 'Google', text: 'Such beautiful photos!!! Marie is a joy to work with! Very professional and knows how to get you comfortable in front of the camera! I\'m so happy with my photo set!' },
  { author: 'Josh W.', rating: 5, source: 'Google', text: 'Marie and her team are simply amazing! The photos are fantastic! She creates a professional yet relaxing environment for taking photos. Thank you Marie!!' },
  { author: 'Matt K.', rating: 5, source: 'Google', text: 'Marie is excellent at what she does. Super professional and very patient. We had a large family shoot with multiple young kids and Marie wasn\'t thrown by it at all. The kids loved her. If you\'re looking for an exceptional photographer that will make your experience easy and fun call Headshots by Marie! I would highly recommend her to anyone.' },
  { author: 'Shaun K.', rating: 5, source: 'Google', text: 'Very professional and head shots turned out great. Marie came to our work location and performed head shots for a number of our staff.' },
  { author: 'Kira H.', rating: 5, source: 'Google', text: 'Marie was amazing. Fantastic experience. Photos are exactly what we needed.' },
  { author: 'Sarah B.', rating: 5, source: 'Google', text: 'I highly recommend Marie for photoshoot. Marie is very easy going and detailed. She will make sure your photo is just right.' },
  { author: 'Randy E.', rating: 5, source: 'Google', text: 'Marie with Headshots by Marie was absolutely amazing! The whole experience from booking the appointment to the photo shoot was a fun, enjoyable and relaxing experience. I would highly recommend Marie for any personal or professional photos you need.' },
  { author: 'Susan K.', rating: 5, source: 'Google', text: 'Really enjoyed the photo shoot!! Marie did an excellent job making sure that I had the professional pictures that I wanted. She is very attentive and also listens!!! Thank you, Marie!' },
  { author: 'Cheryl S.', rating: 5, source: 'Google', text: 'From the moment you walk onto Marie\'s porch you feel welcome. I loved Marie\'s ideas for poses and series of poses. I like how she uses movement in her photos not just placed in seated poses. There were so many great poses in my daughter\'s graduation pictures we had a really hard time narrowing down to just a few pictures! I highly recommend this photographer.' },
  { author: 'Phillip M.', rating: 5, source: 'Google', note: 'SAG actor', text: 'Marie is an excellent photographer! If you hire her you won\'t regret it. FIVE STAR!' },
  { author: 'Kimberly', rating: 5, source: 'Google', text: 'Such a pleasure to work with you Marie, thank you for the amazing head shots. Very professional, quick turn around and amazing attention to detail! Will definitely be working with you again.' },
  { author: 'Jonathan H.', rating: 5, source: 'Google', text: 'Reasonable price.' },
  { author: 'Larry S.', rating: 5, source: 'Google', text: 'Very pleased with my results. Thank you Marie!' },
  { author: 'Maria Z.', rating: 5, source: 'Google', text: 'Loved working with Marie! She is very creative and talented. I highly recommend her!' },
  { author: 'Exclusive Salon', rating: 5, source: 'Google', text: 'Marie is talented and does a great job!' },
  { author: 'Paris S.', rating: 5, source: 'Google', text: 'Marie is such a skilled photographer, her photoshoot helped me feel confident and beautiful. Everything turned out wonderful and it was an incredible and fun experience!' },
  { author: 'Lasheda H.', rating: 5, source: 'Google', text: 'Marie was awesome to work with! She\'s a professional and true artist. She made me feel comfortable during the session and produced some amazing photographs of me. I highly recommend Headshots by Marie. You won\'t be disappointed.' },
  { author: 'Medha J.', rating: 5, source: 'Google', text: 'Marie Feutrier is an amazing photographer and has lots of patience. She takes pictures beautifully and makes you comfortable. She has an eye for the perfect picture. I have wonderful and fun experience during my photo shoot with her.' },
  { author: 'Antonio B.', rating: 5, source: 'Google', text: 'Marie was not only helpful and kind, her work was great and I loved the pictures she produced for me. I would go back with her with any and all portrait needs in a heartbeat. Thanks greatly Marie for your work and your help.' },
  { author: 'Brett Q.', rating: 5, source: 'Google', text: 'Marie truly knows what she is doing! Her strength is she is able to capture the personality of her subject. She makes you feel comfortable immediately and the finished product shows that. I look forward to working with her again.' },
]

export const allReviews: Review[] = [...section1Reviews, ...section2Reviews, ...section3Reviews]

export const REVIEW_COUNT = String(allReviews.length)

// Marketing label, rounded DOWN to the nearest 10 so the claim is always
// conservative and true (90 reviews -> "90+"). Becomes "100+" on its own at 100.
export const REVIEW_COUNT_ROUNDED = `${Math.floor(allReviews.length / 10) * 10}+`
